-- EXAMPLE FOR DELETING A USER
DELETE FROM
  "user"
WHERE
  id = 1;

-- EXAMPLE FOR DELETING A POST
DELETE FROM
  post
WHERE
  id = 1;

-- EXAMPLE FOR DELETING A COMMENT
DELETE FROM
  comment
WHERE
  id = 1;

/* THE IDEAL IDEA SHOULD BE HAVING AN ATTRIBUTE (COLUMN)
 THAT STORES THE DELETED STATE OF AN VALUE
 THAT WAY, DELETING AN USER, POST OR COMMENT WILL ONLY MAKE A CHANGE IN A COLUMN
 USEFUL FOR AVOIDING ERRORS IN THE DATABASE REFERENCES */
UPDATE
  "user"
SET
  deleted = TRUE
WHERE
  id = 1;

UPDATE
  post
SET
  deleted = TRUE
WHERE
  id = 1;

UPDATE
  comment
SET
  deleted = TRUE
WHERE
  id = 1;

/* CAN ALSO DELETE ALL COMMENTS IN A POST, OR DELETE A POST AND LEAVE THE COMMENTS,
 OR DELETE A USER AND LEAVE HIS POSTS, OR DELETE ALL POSTS FROM A USER, OR ALL COMMENTS FROM A USER,
 OR ALL COMMENTS FROM A USER IN CERTAIN POST, OR ALL USERS THAT COMMENTEND ON A CERTAIN POST,
 OR ALL POSTS THAT CONTAIN SOME WORD IN IT, DUE TO THIS BEING A SIMPLE PROJECT, WE WILL ONLY DO THAT
 IF REALLY BECOME CONVENIENT FOR THE PURPOSES OF THE PROJECT */